// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUx17NoXgfkx--iRVSxRhMPGXxy_4XT04',
    appId: '1:610828596105:web:54f3a5b3b517abc5f8a758',
    messagingSenderId: '610828596105',
    projectId: 'puchusapp',
    authDomain: 'puchusapp.firebaseapp.com',
    storageBucket: 'puchusapp.appspot.com',
    measurementId: 'G-SRJVLPSHCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYk8gPDhPOz55HPxTIEOouTZyyDHSPE5Q',
    appId: '1:610828596105:android:493918788818246df8a758',
    messagingSenderId: '610828596105',
    projectId: 'puchusapp',
    storageBucket: 'puchusapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixtd9mcVz28viGZH2kRvcYJ_L5y1iVEM',
    appId: '1:610828596105:ios:6d72c10022b117e9f8a758',
    messagingSenderId: '610828596105',
    projectId: 'puchusapp',
    storageBucket: 'puchusapp.appspot.com',
    iosClientId: '610828596105-0pj9lgsrd5a7pbp0lftnsgqqfoh73a0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixtd9mcVz28viGZH2kRvcYJ_L5y1iVEM',
    appId: '1:610828596105:ios:bbb64cb07bf7e21af8a758',
    messagingSenderId: '610828596105',
    projectId: 'puchusapp',
    storageBucket: 'puchusapp.appspot.com',
    iosClientId: '610828596105-5runkalcfbf2t9p0r2qlblt64mt6h65s.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneui.RunnerTests',
  );
}
